version: 2.1

jobs:
  build:
    working_directory: ~/odk-x-droid
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew build

  deploy:
    working_directory: ~/odk-x-droid
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run: echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc
      - run: ./gradlew publishToGitHubPackagesRepository

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
