version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/android:2023.02
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: permmissions
          command: chmod +x ./gradlew
      - run:
          name: Install dependencies
          command: ./gradlew androidDependencies
          
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      - run:
          name: Build project
          command: ./gradlew clean assemble
      - run:
          name: Run unit tests
          command: ./gradlew test

      - run:
          name: Authenticate with GitHub Packages
          command: |
            echo "//maven.pkg.github.com/tr-sangale/odk-x-droid/:username=tr-sangale" >> ~/.gradle/gradle.properties
            echo "//maven.pkg.github.com/tr-sangale/odk-x-droid/:password=${GITHUB_TOKEN}" >> ~/.gradle/gradle.properties
            
      - run:
          name: Publish library to GitHub Packages
          command: |
             mvn clean deploy

      
workflows:
  build:
    jobs:
      - build
















